In [32]:
# Task_3 - Email Spam Detection

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [38]:
df=pd.read_csv("spam.csv")
df.head(10)

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [3]:
df.shape

(5572, 5)

In [4]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [18]:
df['spam']=df['v1'].apply(lambda x: 1 if x=='spam' else 0)

In [19]:
df1=df.drop(df[['Unnamed: 2','Unnamed: 3','Unnamed: 4']],axis="columns")

In [39]:
df1.head(10)

category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

In [40]:
df1.rename(columns={'v1':'category','v2':'message'},inplace=True)
df1.head(10)

category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

In [10]:
from sklearn.model_selection import train_test_split


In [22]:
X_train, X_test, y_train, y_test=train_test_split(df1.message,df.spam,test_size=0.25)

In [23]:
X_train.head()

1996                     Lol boo I was hoping for a laugh
3810          Excellent! Wish we were together right now!
1799         If we hit it off, you can move in with me :)
1658    RGENT! This is the 2nd attempt to contact U!U ...
5234                                Ok cool. See ya then.
Name: message, dtype: object

In [24]:
y_train.head()

1996    0
3810    0
1799    0
1658    1
5234    0
Name: spam, dtype: int64

In [25]:
# Now we will convert text data ..

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [27]:
# Now we will train our model 

In [28]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [29]:
#Now we will test and predict some input emails

In [30]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [37]:
# We can test this on multiple test dataset emails 
model.predict(X_test_count)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [31]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

0.9856424982053122

In [ ]:
# Thank You !!